/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as ProtectedAgentRouteImport } from './routes/_protected/agent'
import { Route as ProtectedCompareRouteImport } from './routes/_protected/compare'
import { Route as ProtectedCustomerRouteImport } from './routes/_protected/customer'
import { Route as ProtectedDebugRouteImport } from './routes/_protected/debug'
import { Route as ProtectedEksporRouteImport } from './routes/_protected/ekspor'
import { Route as ProtectedSkenarioRouteImport } from './routes/_protected/skenario'
import { Route as ProtectedTestSetRouteImport } from './routes/_protected/test-set'
import { Route as ApiSuggestionsRouteImport } from './routes/api/suggestions'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiConversationsIndexRouteImport } from './routes/api/conversations/index'
import { Route as ApiConversationsCurrentRouteImport } from './routes/api/conversations/current'
import { Route as ApiExportsSummaryRouteImport } from './routes/api/exports/summary'
import { Route as ApiExportsTranscriptRouteImport } from './routes/api/exports/transcript'
import { Route as ApiNotesIndexRouteImport } from './routes/api/notes/index'
import { Route as ApiNotesIdRouteImport } from './routes/api/notes/$id'
import { Route as ApiScenariosIndexRouteImport } from './routes/api/scenarios/index'
import { Route as ApiScenariosBatchRouteImport } from './routes/api/scenarios/batch'
import { Route as ApiTestRunsIndexRouteImport } from './routes/api/test-runs/index'
import { Route as ApiTestSetsIndexRouteImport } from './routes/api/test-sets/index'
import { Route as ApiTicketsIndexRouteImport } from './routes/api/tickets/index'
import { Route as ApiAdminNotesIndexRouteImport } from './routes/api/admin/notes/index'
import { Route as ApiAdminNotesIdRouteImport } from './routes/api/admin/notes/$id'
import { Route as ApiConversationsIdIndexRouteImport } from './routes/api/conversations/$id/index'
import { Route as ApiConversationsIdComparisonRouteImport } from './routes/api/conversations/$id/comparison'
import { Route as ApiConversationsIdDebugRouteImport } from './routes/api/conversations/$id/debug'
import { Route as ApiConversationsIdEventsRouteImport } from './routes/api/conversations/$id/events'
import { Route as ApiConversationsIdMessagesRouteImport } from './routes/api/conversations/$id/messages'
import { Route as ApiConversationsIdSummaryRouteImport } from './routes/api/conversations/$id/summary'
import { Route as ApiScenariosIdRunRouteImport } from './routes/api/scenarios/$id/run'
import { Route as ApiTestRunsIdIndexRouteImport } from './routes/api/test-runs/$id/index'
import { Route as ApiTestRunsIdCancelRouteImport } from './routes/api/test-runs/$id/cancel'
import { Route as ApiTestRunsIdComparisonRouteImport } from './routes/api/test-runs/$id/comparison'
import { Route as ApiTestRunsIdEventsRouteImport } from './routes/api/test-runs/$id/events'
import { Route as ApiTestRunsIdReportRouteImport } from './routes/api/test-runs/$id/report'
import { Route as ApiTicketsIdIndexRouteImport } from './routes/api/tickets/$id/index'
import { Route as ApiTicketsIdRepliesRouteImport } from './routes/api/tickets/$id/replies'
import { Route as ApiTicketsIdSummaryRouteImport } from './routes/api/tickets/$id/summary'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAgentRoute = ProtectedAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCompareRoute = ProtectedCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCustomerRoute = ProtectedCustomerRouteImport.update({
  id: '/customer',
  path: '/customer',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDebugRoute = ProtectedDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedEksporRoute = ProtectedEksporRouteImport.update({
  id: '/ekspor',
  path: '/ekspor',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSkenarioRoute = ProtectedSkenarioRouteImport.update({
  id: '/skenario',
  path: '/skenario',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTestSetRoute = ProtectedTestSetRouteImport.update({
  id: '/test-set',
  path: '/test-set',
  getParentRoute: () => ProtectedRoute,
} as any)
const ApiSuggestionsRoute = ApiSuggestionsRouteImport.update({
  id: '/api/suggestions',
  path: '/api/suggestions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIndexRoute = ApiConversationsIndexRouteImport.update({
  id: '/api/conversations/',
  path: '/api/conversations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsCurrentRoute = ApiConversationsCurrentRouteImport.update({
  id: '/api/conversations/current',
  path: '/api/conversations/current',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsSummaryRoute = ApiExportsSummaryRouteImport.update({
  id: '/api/exports/summary',
  path: '/api/exports/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExportsTranscriptRoute = ApiExportsTranscriptRouteImport.update({
  id: '/api/exports/transcript',
  path: '/api/exports/transcript',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIndexRoute = ApiNotesIndexRouteImport.update({
  id: '/api/notes/',
  path: '/api/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotesIdRoute = ApiNotesIdRouteImport.update({
  id: '/api/notes/$id',
  path: '/api/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScenariosIndexRoute = ApiScenariosIndexRouteImport.update({
  id: '/api/scenarios/',
  path: '/api/scenarios/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScenariosBatchRoute = ApiScenariosBatchRouteImport.update({
  id: '/api/scenarios/batch',
  path: '/api/scenarios/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRunsIndexRoute = ApiTestRunsIndexRouteImport.update({
  id: '/api/test-runs/',
  path: '/api/test-runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestSetsIndexRoute = ApiTestSetsIndexRouteImport.update({
  id: '/api/test-sets/',
  path: '/api/test-sets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsIndexRoute = ApiTicketsIndexRouteImport.update({
  id: '/api/tickets/',
  path: '/api/tickets/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotesIndexRoute = ApiAdminNotesIndexRouteImport.update({
  id: '/api/admin/notes/',
  path: '/api/admin/notes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminNotesIdRoute = ApiAdminNotesIdRouteImport.update({
  id: '/api/admin/notes/$id',
  path: '/api/admin/notes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdIndexRoute = ApiConversationsIdIndexRouteImport.update({
  id: '/api/conversations/$id/',
  path: '/api/conversations/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdComparisonRoute =
  ApiConversationsIdComparisonRouteImport.update({
    id: '/api/conversations/$id/comparison',
    path: '/api/conversations/$id/comparison',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationsIdDebugRoute = ApiConversationsIdDebugRouteImport.update({
  id: '/api/conversations/$id/debug',
  path: '/api/conversations/$id/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConversationsIdEventsRoute =
  ApiConversationsIdEventsRouteImport.update({
    id: '/api/conversations/$id/events',
    path: '/api/conversations/$id/events',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationsIdMessagesRoute =
  ApiConversationsIdMessagesRouteImport.update({
    id: '/api/conversations/$id/messages',
    path: '/api/conversations/$id/messages',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiConversationsIdSummaryRoute =
  ApiConversationsIdSummaryRouteImport.update({
    id: '/api/conversations/$id/summary',
    path: '/api/conversations/$id/summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiScenariosIdRunRoute = ApiScenariosIdRunRouteImport.update({
  id: '/api/scenarios/$id/run',
  path: '/api/scenarios/$id/run',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRunsIdIndexRoute = ApiTestRunsIdIndexRouteImport.update({
  id: '/api/test-runs/$id/',
  path: '/api/test-runs/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRunsIdCancelRoute = ApiTestRunsIdCancelRouteImport.update({
  id: '/api/test-runs/$id/cancel',
  path: '/api/test-runs/$id/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRunsIdComparisonRoute = ApiTestRunsIdComparisonRouteImport.update({
  id: '/api/test-runs/$id/comparison',
  path: '/api/test-runs/$id/comparison',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRunsIdEventsRoute = ApiTestRunsIdEventsRouteImport.update({
  id: '/api/test-runs/$id/events',
  path: '/api/test-runs/$id/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTestRunsIdReportRoute = ApiTestRunsIdReportRouteImport.update({
  id: '/api/test-runs/$id/report',
  path: '/api/test-runs/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsIdIndexRoute = ApiTicketsIdIndexRouteImport.update({
  id: '/api/tickets/$id/',
  path: '/api/tickets/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsIdRepliesRoute = ApiTicketsIdRepliesRouteImport.update({
  id: '/api/tickets/$id/replies',
  path: '/api/tickets/$id/replies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTicketsIdSummaryRoute = ApiTicketsIdSummaryRouteImport.update({
  id: '/api/tickets/$id/summary',
  path: '/api/tickets/$id/summary',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRoute
  '/agent': typeof ProtectedAgentRoute
  '/compare': typeof ProtectedCompareRoute
  '/customer': typeof ProtectedCustomerRoute
  '/debug': typeof ProtectedDebugRoute
  '/ekspor': typeof ProtectedEksporRoute
  '/skenario': typeof ProtectedSkenarioRoute
  '/test-set': typeof ProtectedTestSetRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/current': typeof ApiConversationsCurrentRoute
  '/api/exports/summary': typeof ApiExportsSummaryRoute
  '/api/exports/transcript': typeof ApiExportsTranscriptRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/scenarios/batch': typeof ApiScenariosBatchRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/scenarios/': typeof ApiScenariosIndexRoute
  '/api/test-runs/': typeof ApiTestRunsIndexRoute
  '/api/test-sets/': typeof ApiTestSetsIndexRoute
  '/api/tickets/': typeof ApiTicketsIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/conversations/$id/comparison': typeof ApiConversationsIdComparisonRoute
  '/api/conversations/$id/debug': typeof ApiConversationsIdDebugRoute
  '/api/conversations/$id/events': typeof ApiConversationsIdEventsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/summary': typeof ApiConversationsIdSummaryRoute
  '/api/scenarios/$id/run': typeof ApiScenariosIdRunRoute
  '/api/test-runs/$id/cancel': typeof ApiTestRunsIdCancelRoute
  '/api/test-runs/$id/comparison': typeof ApiTestRunsIdComparisonRoute
  '/api/test-runs/$id/events': typeof ApiTestRunsIdEventsRoute
  '/api/test-runs/$id/report': typeof ApiTestRunsIdReportRoute
  '/api/tickets/$id/replies': typeof ApiTicketsIdRepliesRoute
  '/api/tickets/$id/summary': typeof ApiTicketsIdSummaryRoute
  '/api/admin/notes/': typeof ApiAdminNotesIndexRoute
  '/api/conversations/$id/': typeof ApiConversationsIdIndexRoute
  '/api/test-runs/$id/': typeof ApiTestRunsIdIndexRoute
  '/api/tickets/$id/': typeof ApiTicketsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRoute
  '/agent': typeof ProtectedAgentRoute
  '/compare': typeof ProtectedCompareRoute
  '/customer': typeof ProtectedCustomerRoute
  '/debug': typeof ProtectedDebugRoute
  '/ekspor': typeof ProtectedEksporRoute
  '/skenario': typeof ProtectedSkenarioRoute
  '/test-set': typeof ProtectedTestSetRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/current': typeof ApiConversationsCurrentRoute
  '/api/exports/summary': typeof ApiExportsSummaryRoute
  '/api/exports/transcript': typeof ApiExportsTranscriptRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/scenarios/batch': typeof ApiScenariosBatchRoute
  '/api/conversations': typeof ApiConversationsIndexRoute
  '/api/notes': typeof ApiNotesIndexRoute
  '/api/scenarios': typeof ApiScenariosIndexRoute
  '/api/test-runs': typeof ApiTestRunsIndexRoute
  '/api/test-sets': typeof ApiTestSetsIndexRoute
  '/api/tickets': typeof ApiTicketsIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/conversations/$id/comparison': typeof ApiConversationsIdComparisonRoute
  '/api/conversations/$id/debug': typeof ApiConversationsIdDebugRoute
  '/api/conversations/$id/events': typeof ApiConversationsIdEventsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/summary': typeof ApiConversationsIdSummaryRoute
  '/api/scenarios/$id/run': typeof ApiScenariosIdRunRoute
  '/api/test-runs/$id/cancel': typeof ApiTestRunsIdCancelRoute
  '/api/test-runs/$id/comparison': typeof ApiTestRunsIdComparisonRoute
  '/api/test-runs/$id/events': typeof ApiTestRunsIdEventsRoute
  '/api/test-runs/$id/report': typeof ApiTestRunsIdReportRoute
  '/api/tickets/$id/replies': typeof ApiTicketsIdRepliesRoute
  '/api/tickets/$id/summary': typeof ApiTicketsIdSummaryRoute
  '/api/admin/notes': typeof ApiAdminNotesIndexRoute
  '/api/conversations/$id': typeof ApiConversationsIdIndexRoute
  '/api/test-runs/$id': typeof ApiTestRunsIdIndexRoute
  '/api/tickets/$id': typeof ApiTicketsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/admin': typeof ProtectedAdminRoute
  '/_protected/agent': typeof ProtectedAgentRoute
  '/_protected/compare': typeof ProtectedCompareRoute
  '/_protected/customer': typeof ProtectedCustomerRoute
  '/_protected/debug': typeof ProtectedDebugRoute
  '/_protected/ekspor': typeof ProtectedEksporRoute
  '/_protected/skenario': typeof ProtectedSkenarioRoute
  '/_protected/test-set': typeof ProtectedTestSetRoute
  '/api/suggestions': typeof ApiSuggestionsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/conversations/current': typeof ApiConversationsCurrentRoute
  '/api/exports/summary': typeof ApiExportsSummaryRoute
  '/api/exports/transcript': typeof ApiExportsTranscriptRoute
  '/api/notes/$id': typeof ApiNotesIdRoute
  '/api/scenarios/batch': typeof ApiScenariosBatchRoute
  '/api/conversations/': typeof ApiConversationsIndexRoute
  '/api/notes/': typeof ApiNotesIndexRoute
  '/api/scenarios/': typeof ApiScenariosIndexRoute
  '/api/test-runs/': typeof ApiTestRunsIndexRoute
  '/api/test-sets/': typeof ApiTestSetsIndexRoute
  '/api/tickets/': typeof ApiTicketsIndexRoute
  '/api/admin/notes/$id': typeof ApiAdminNotesIdRoute
  '/api/conversations/$id/comparison': typeof ApiConversationsIdComparisonRoute
  '/api/conversations/$id/debug': typeof ApiConversationsIdDebugRoute
  '/api/conversations/$id/events': typeof ApiConversationsIdEventsRoute
  '/api/conversations/$id/messages': typeof ApiConversationsIdMessagesRoute
  '/api/conversations/$id/summary': typeof ApiConversationsIdSummaryRoute
  '/api/scenarios/$id/run': typeof ApiScenariosIdRunRoute
  '/api/test-runs/$id/cancel': typeof ApiTestRunsIdCancelRoute
  '/api/test-runs/$id/comparison': typeof ApiTestRunsIdComparisonRoute
  '/api/test-runs/$id/events': typeof ApiTestRunsIdEventsRoute
  '/api/test-runs/$id/report': typeof ApiTestRunsIdReportRoute
  '/api/tickets/$id/replies': typeof ApiTicketsIdRepliesRoute
  '/api/tickets/$id/summary': typeof ApiTicketsIdSummaryRoute
  '/api/admin/notes/': typeof ApiAdminNotesIndexRoute
  '/api/conversations/$id/': typeof ApiConversationsIdIndexRoute
  '/api/test-runs/$id/': typeof ApiTestRunsIdIndexRoute
  '/api/tickets/$id/': typeof ApiTicketsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/agent'
    | '/compare'
    | '/customer'
    | '/debug'
    | '/ekspor'
    | '/skenario'
    | '/test-set'
    | '/api/suggestions'
    | '/api/auth/$'
    | '/api/conversations/current'
    | '/api/exports/summary'
    | '/api/exports/transcript'
    | '/api/notes/$id'
    | '/api/scenarios/batch'
    | '/api/conversations/'
    | '/api/notes/'
    | '/api/scenarios/'
    | '/api/test-runs/'
    | '/api/test-sets/'
    | '/api/tickets/'
    | '/api/admin/notes/$id'
    | '/api/conversations/$id/comparison'
    | '/api/conversations/$id/debug'
    | '/api/conversations/$id/events'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/summary'
    | '/api/scenarios/$id/run'
    | '/api/test-runs/$id/cancel'
    | '/api/test-runs/$id/comparison'
    | '/api/test-runs/$id/events'
    | '/api/test-runs/$id/report'
    | '/api/tickets/$id/replies'
    | '/api/tickets/$id/summary'
    | '/api/admin/notes/'
    | '/api/conversations/$id/'
    | '/api/test-runs/$id/'
    | '/api/tickets/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/admin'
    | '/agent'
    | '/compare'
    | '/customer'
    | '/debug'
    | '/ekspor'
    | '/skenario'
    | '/test-set'
    | '/api/suggestions'
    | '/api/auth/$'
    | '/api/conversations/current'
    | '/api/exports/summary'
    | '/api/exports/transcript'
    | '/api/notes/$id'
    | '/api/scenarios/batch'
    | '/api/conversations'
    | '/api/notes'
    | '/api/scenarios'
    | '/api/test-runs'
    | '/api/test-sets'
    | '/api/tickets'
    | '/api/admin/notes/$id'
    | '/api/conversations/$id/comparison'
    | '/api/conversations/$id/debug'
    | '/api/conversations/$id/events'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/summary'
    | '/api/scenarios/$id/run'
    | '/api/test-runs/$id/cancel'
    | '/api/test-runs/$id/comparison'
    | '/api/test-runs/$id/events'
    | '/api/test-runs/$id/report'
    | '/api/tickets/$id/replies'
    | '/api/tickets/$id/summary'
    | '/api/admin/notes'
    | '/api/conversations/$id'
    | '/api/test-runs/$id'
    | '/api/tickets/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_protected'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_protected/admin'
    | '/_protected/agent'
    | '/_protected/compare'
    | '/_protected/customer'
    | '/_protected/debug'
    | '/_protected/ekspor'
    | '/_protected/skenario'
    | '/_protected/test-set'
    | '/api/suggestions'
    | '/api/auth/$'
    | '/api/conversations/current'
    | '/api/exports/summary'
    | '/api/exports/transcript'
    | '/api/notes/$id'
    | '/api/scenarios/batch'
    | '/api/conversations/'
    | '/api/notes/'
    | '/api/scenarios/'
    | '/api/test-runs/'
    | '/api/test-sets/'
    | '/api/tickets/'
    | '/api/admin/notes/$id'
    | '/api/conversations/$id/comparison'
    | '/api/conversations/$id/debug'
    | '/api/conversations/$id/events'
    | '/api/conversations/$id/messages'
    | '/api/conversations/$id/summary'
    | '/api/scenarios/$id/run'
    | '/api/test-runs/$id/cancel'
    | '/api/test-runs/$id/comparison'
    | '/api/test-runs/$id/events'
    | '/api/test-runs/$id/report'
    | '/api/tickets/$id/replies'
    | '/api/tickets/$id/summary'
    | '/api/admin/notes/'
    | '/api/conversations/$id/'
    | '/api/test-runs/$id/'
    | '/api/tickets/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ApiSuggestionsRoute: typeof ApiSuggestionsRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiConversationsCurrentRoute: typeof ApiConversationsCurrentRoute
  ApiExportsSummaryRoute: typeof ApiExportsSummaryRoute
  ApiExportsTranscriptRoute: typeof ApiExportsTranscriptRoute
  ApiNotesIdRoute: typeof ApiNotesIdRoute
  ApiScenariosBatchRoute: typeof ApiScenariosBatchRoute
  ApiConversationsIndexRoute: typeof ApiConversationsIndexRoute
  ApiNotesIndexRoute: typeof ApiNotesIndexRoute
  ApiScenariosIndexRoute: typeof ApiScenariosIndexRoute
  ApiTestRunsIndexRoute: typeof ApiTestRunsIndexRoute
  ApiTestSetsIndexRoute: typeof ApiTestSetsIndexRoute
  ApiTicketsIndexRoute: typeof ApiTicketsIndexRoute
  ApiAdminNotesIdRoute: typeof ApiAdminNotesIdRoute
  ApiConversationsIdComparisonRoute: typeof ApiConversationsIdComparisonRoute
  ApiConversationsIdDebugRoute: typeof ApiConversationsIdDebugRoute
  ApiConversationsIdEventsRoute: typeof ApiConversationsIdEventsRoute
  ApiConversationsIdMessagesRoute: typeof ApiConversationsIdMessagesRoute
  ApiConversationsIdSummaryRoute: typeof ApiConversationsIdSummaryRoute
  ApiScenariosIdRunRoute: typeof ApiScenariosIdRunRoute
  ApiTestRunsIdCancelRoute: typeof ApiTestRunsIdCancelRoute
  ApiTestRunsIdComparisonRoute: typeof ApiTestRunsIdComparisonRoute
  ApiTestRunsIdEventsRoute: typeof ApiTestRunsIdEventsRoute
  ApiTestRunsIdReportRoute: typeof ApiTestRunsIdReportRoute
  ApiTicketsIdRepliesRoute: typeof ApiTicketsIdRepliesRoute
  ApiTicketsIdSummaryRoute: typeof ApiTicketsIdSummaryRoute
  ApiAdminNotesIndexRoute: typeof ApiAdminNotesIndexRoute
  ApiConversationsIdIndexRoute: typeof ApiConversationsIdIndexRoute
  ApiTestRunsIdIndexRoute: typeof ApiTestRunsIdIndexRoute
  ApiTicketsIdIndexRoute: typeof ApiTicketsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/agent': {
      id: '/_protected/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof ProtectedAgentRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/compare': {
      id: '/_protected/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof ProtectedCompareRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/customer': {
      id: '/_protected/customer'
      path: '/customer'
      fullPath: '/customer'
      preLoaderRoute: typeof ProtectedCustomerRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/debug': {
      id: '/_protected/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof ProtectedDebugRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/ekspor': {
      id: '/_protected/ekspor'
      path: '/ekspor'
      fullPath: '/ekspor'
      preLoaderRoute: typeof ProtectedEksporRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/skenario': {
      id: '/_protected/skenario'
      path: '/skenario'
      fullPath: '/skenario'
      preLoaderRoute: typeof ProtectedSkenarioRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/test-set': {
      id: '/_protected/test-set'
      path: '/test-set'
      fullPath: '/test-set'
      preLoaderRoute: typeof ProtectedTestSetRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/api/suggestions': {
      id: '/api/suggestions'
      path: '/api/suggestions'
      fullPath: '/api/suggestions'
      preLoaderRoute: typeof ApiSuggestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/': {
      id: '/api/conversations/'
      path: '/api/conversations'
      fullPath: '/api/conversations/'
      preLoaderRoute: typeof ApiConversationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/current': {
      id: '/api/conversations/current'
      path: '/api/conversations/current'
      fullPath: '/api/conversations/current'
      preLoaderRoute: typeof ApiConversationsCurrentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/summary': {
      id: '/api/exports/summary'
      path: '/api/exports/summary'
      fullPath: '/api/exports/summary'
      preLoaderRoute: typeof ApiExportsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/exports/transcript': {
      id: '/api/exports/transcript'
      path: '/api/exports/transcript'
      fullPath: '/api/exports/transcript'
      preLoaderRoute: typeof ApiExportsTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/': {
      id: '/api/notes/'
      path: '/api/notes'
      fullPath: '/api/notes/'
      preLoaderRoute: typeof ApiNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notes/$id': {
      id: '/api/notes/$id'
      path: '/api/notes/$id'
      fullPath: '/api/notes/$id'
      preLoaderRoute: typeof ApiNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenarios/': {
      id: '/api/scenarios/'
      path: '/api/scenarios'
      fullPath: '/api/scenarios/'
      preLoaderRoute: typeof ApiScenariosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenarios/batch': {
      id: '/api/scenarios/batch'
      path: '/api/scenarios/batch'
      fullPath: '/api/scenarios/batch'
      preLoaderRoute: typeof ApiScenariosBatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-runs/': {
      id: '/api/test-runs/'
      path: '/api/test-runs'
      fullPath: '/api/test-runs/'
      preLoaderRoute: typeof ApiTestRunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-sets/': {
      id: '/api/test-sets/'
      path: '/api/test-sets'
      fullPath: '/api/test-sets/'
      preLoaderRoute: typeof ApiTestSetsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/': {
      id: '/api/tickets/'
      path: '/api/tickets'
      fullPath: '/api/tickets/'
      preLoaderRoute: typeof ApiTicketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notes/': {
      id: '/api/admin/notes/'
      path: '/api/admin/notes'
      fullPath: '/api/admin/notes/'
      preLoaderRoute: typeof ApiAdminNotesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/notes/$id': {
      id: '/api/admin/notes/$id'
      path: '/api/admin/notes/$id'
      fullPath: '/api/admin/notes/$id'
      preLoaderRoute: typeof ApiAdminNotesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/': {
      id: '/api/conversations/$id/'
      path: '/api/conversations/$id'
      fullPath: '/api/conversations/$id/'
      preLoaderRoute: typeof ApiConversationsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/comparison': {
      id: '/api/conversations/$id/comparison'
      path: '/api/conversations/$id/comparison'
      fullPath: '/api/conversations/$id/comparison'
      preLoaderRoute: typeof ApiConversationsIdComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/debug': {
      id: '/api/conversations/$id/debug'
      path: '/api/conversations/$id/debug'
      fullPath: '/api/conversations/$id/debug'
      preLoaderRoute: typeof ApiConversationsIdDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/events': {
      id: '/api/conversations/$id/events'
      path: '/api/conversations/$id/events'
      fullPath: '/api/conversations/$id/events'
      preLoaderRoute: typeof ApiConversationsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/messages': {
      id: '/api/conversations/$id/messages'
      path: '/api/conversations/$id/messages'
      fullPath: '/api/conversations/$id/messages'
      preLoaderRoute: typeof ApiConversationsIdMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/conversations/$id/summary': {
      id: '/api/conversations/$id/summary'
      path: '/api/conversations/$id/summary'
      fullPath: '/api/conversations/$id/summary'
      preLoaderRoute: typeof ApiConversationsIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scenarios/$id/run': {
      id: '/api/scenarios/$id/run'
      path: '/api/scenarios/$id/run'
      fullPath: '/api/scenarios/$id/run'
      preLoaderRoute: typeof ApiScenariosIdRunRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-runs/$id/': {
      id: '/api/test-runs/$id/'
      path: '/api/test-runs/$id'
      fullPath: '/api/test-runs/$id/'
      preLoaderRoute: typeof ApiTestRunsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-runs/$id/cancel': {
      id: '/api/test-runs/$id/cancel'
      path: '/api/test-runs/$id/cancel'
      fullPath: '/api/test-runs/$id/cancel'
      preLoaderRoute: typeof ApiTestRunsIdCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-runs/$id/comparison': {
      id: '/api/test-runs/$id/comparison'
      path: '/api/test-runs/$id/comparison'
      fullPath: '/api/test-runs/$id/comparison'
      preLoaderRoute: typeof ApiTestRunsIdComparisonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-runs/$id/events': {
      id: '/api/test-runs/$id/events'
      path: '/api/test-runs/$id/events'
      fullPath: '/api/test-runs/$id/events'
      preLoaderRoute: typeof ApiTestRunsIdEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/test-runs/$id/report': {
      id: '/api/test-runs/$id/report'
      path: '/api/test-runs/$id/report'
      fullPath: '/api/test-runs/$id/report'
      preLoaderRoute: typeof ApiTestRunsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/$id/': {
      id: '/api/tickets/$id/'
      path: '/api/tickets/$id'
      fullPath: '/api/tickets/$id/'
      preLoaderRoute: typeof ApiTicketsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/$id/replies': {
      id: '/api/tickets/$id/replies'
      path: '/api/tickets/$id/replies'
      fullPath: '/api/tickets/$id/replies'
      preLoaderRoute: typeof ApiTicketsIdRepliesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tickets/$id/summary': {
      id: '/api/tickets/$id/summary'
      path: '/api/tickets/$id/summary'
      fullPath: '/api/tickets/$id/summary'
      preLoaderRoute: typeof ApiTicketsIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRoute
  ProtectedAgentRoute: typeof ProtectedAgentRoute
  ProtectedCompareRoute: typeof ProtectedCompareRoute
  ProtectedCustomerRoute: typeof ProtectedCustomerRoute
  ProtectedDebugRoute: typeof ProtectedDebugRoute
  ProtectedEksporRoute: typeof ProtectedEksporRoute
  ProtectedSkenarioRoute: typeof ProtectedSkenarioRoute
  ProtectedTestSetRoute: typeof ProtectedTestSetRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRoute,
  ProtectedAgentRoute: ProtectedAgentRoute,
  ProtectedCompareRoute: ProtectedCompareRoute,
  ProtectedCustomerRoute: ProtectedCustomerRoute,
  ProtectedDebugRoute: ProtectedDebugRoute,
  ProtectedEksporRoute: ProtectedEksporRoute,
  ProtectedSkenarioRoute: ProtectedSkenarioRoute,
  ProtectedTestSetRoute: ProtectedTestSetRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  ApiSuggestionsRoute: ApiSuggestionsRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiConversationsCurrentRoute: ApiConversationsCurrentRoute,
  ApiExportsSummaryRoute: ApiExportsSummaryRoute,
  ApiExportsTranscriptRoute: ApiExportsTranscriptRoute,
  ApiNotesIdRoute: ApiNotesIdRoute,
  ApiScenariosBatchRoute: ApiScenariosBatchRoute,
  ApiConversationsIndexRoute: ApiConversationsIndexRoute,
  ApiNotesIndexRoute: ApiNotesIndexRoute,
  ApiScenariosIndexRoute: ApiScenariosIndexRoute,
  ApiTestRunsIndexRoute: ApiTestRunsIndexRoute,
  ApiTestSetsIndexRoute: ApiTestSetsIndexRoute,
  ApiTicketsIndexRoute: ApiTicketsIndexRoute,
  ApiAdminNotesIdRoute: ApiAdminNotesIdRoute,
  ApiConversationsIdComparisonRoute: ApiConversationsIdComparisonRoute,
  ApiConversationsIdDebugRoute: ApiConversationsIdDebugRoute,
  ApiConversationsIdEventsRoute: ApiConversationsIdEventsRoute,
  ApiConversationsIdMessagesRoute: ApiConversationsIdMessagesRoute,
  ApiConversationsIdSummaryRoute: ApiConversationsIdSummaryRoute,
  ApiScenariosIdRunRoute: ApiScenariosIdRunRoute,
  ApiTestRunsIdCancelRoute: ApiTestRunsIdCancelRoute,
  ApiTestRunsIdComparisonRoute: ApiTestRunsIdComparisonRoute,
  ApiTestRunsIdEventsRoute: ApiTestRunsIdEventsRoute,
  ApiTestRunsIdReportRoute: ApiTestRunsIdReportRoute,
  ApiTicketsIdRepliesRoute: ApiTicketsIdRepliesRoute,
  ApiTicketsIdSummaryRoute: ApiTicketsIdSummaryRoute,
  ApiAdminNotesIndexRoute: ApiAdminNotesIndexRoute,
  ApiConversationsIdIndexRoute: ApiConversationsIdIndexRoute,
  ApiTestRunsIdIndexRoute: ApiTestRunsIdIndexRoute,
  ApiTicketsIdIndexRoute: ApiTicketsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
